### ISSUE TITLE
uCEFBrowserBitmap

### ISSUE THREAD

**Issue by limelect** [EricGrange/cefHtmlSnapshot#5]
uCEFBrowserBitmap missing

**Comment by EricGrange** [comment]
It's part of CEF4Delphi (source/uCEFBrowserBitmap.pas)

https://github.com/salvadordf/CEF4Delphi/blob/d93b699712892b8afe10d7de057843d4fbf89a54/source/uCEFBrowserBitmap.pas

**Comment by limelect** [comment]
Thanks
