### ISSUE TITLE
Unfortunately

### ISSUE THREAD

**Issue by limelect** [EricGrange/cefHtmlSnapshot#6]
Unfortunately, I can not use your new source as it relies
on the new Delphi
I fixed the VAR but there are still a lot of errors.
I am using D10.2.3
Thanks
I have even seen D5 around which means you expect to buy new Delphi every time 
Also for example

error not exist
FBrowserBitmap.UpdateBufferDimensions 
FBrowserBitmap.UpdateBufferDimensions
FBrowserBitmap.BeginBufferDraw
  FBrowser.OnBeforePopup           := Browser_OnBeforePopup;      parameter differ

and maybe more

P.S I had timing problem with getting a site with the old version so I thought the newone
will help

**Comment by EricGrange** [comment]
Unfortunately I only have access to Delphi 12 and community edition
